### PR TITLE
Updates ruby_extensions.rb to not mutate the String class and use a S…

### PR DESCRIPTION
**Pull request by ncavig**
…tringHelper module so collisions do not happen on the String#underscore method (Rails)

### CODE REVIEW

**Comment by ncavig** [comment]
Defining String#underscore breaks core Rails String extensions when dealing with acronyms. I changed the `ruby_extensions.rb` file to use a module helper instead of defining `#underscore` on `String`. Another option could be to do something like

``` ruby
class String
  def underscore
    return super if defined?(super)

    str.gsub(/::/, '/').
        gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2').
        gsub(/([a-z\d])([A-Z])/, '\1_\2').
        tr("-", "_").
        downcase
  end
end
```

I just think since underscore is used only in your `Hash#to_open_struct` it doesn't warrant a String method definition. 

Comments or feedback welcome.

**Comment by johnnyshields** [comment]
It would be better not to monkey patch string at all and move this inside the `Googl` gem namespace.

**Comment by bessey** [comment]
Just to back @johnnyshields comment up, I have discovered that the core extensions actually break the gem `graphiql-rails` entirely, and it was only dumb luck that we introduced this gem after `graphiql-rails`, or we may never have worked out why it broke!

**Comment by ncavig** [comment]
We forked the repo and included my patch if you want to use or fork yourself at https://github.com/RealScout/googl

**Comment by ncavig** [comment]
Closing because it's been a long time and google url shortener has been deprecated

**Pull request closed without merging**
